name: lineseg_env
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python=3.7.3
- anaconda::tensorflow-gpu=2.2.0
- anaconda::pyyaml=5.3.1
- anaconda::pillow=7.1.2
- anaconda::pandas=1.1.3
- anaconda::scikit-learn=0.22.1
- conda-forge::tqdm=4.50.2
- conda-forge::matplotlib=3.3.3