name: lineseg_env
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python=3.7.3
- anaconda::pip=20.2.2
- anaconda::pyyaml=5.3.1
- anaconda::pillow=7.1.2
- anaconda::pandas=1.0.3
- anaconda::scikit-learn=0.22.1
- conda-forge::tqdm=4.38
- conda-forge::matplotlib=3.2.1
- conda-forge::shapely=1.7.0
- pip:
    - tensorflow==2.1.0
