# The path to the directory of images to be inferred
img_path: ./data/test_images
# Include subdirectories of img_path, if set to False any directories within img_path will be ignored
img_path_subdirs: False
# The path to the directory that segmented line snippets will be stored
out_path: ./data/out/example/snippets
# The path to the pre-trained model weights
model_in: ./data/model_weights/lineseg_model/run1
# Whether or not to save the original coordinate information in each individual line snippet's name
coordinate_naming: True
# Whether or not to save the raw output of the semantic segmentation model
save_raw: True
# The path to the directory that the raw output images will be stored
raw_path: ./data/out/example/raw

# The size which all images will be resized for inference
img_size: (1024, 1536)
# The size of the mini-batch used during inference
batch_size: 1
