package:
  name: lineseg
  version: 0.1

source:
  git_rev: master
  git_url: https://github.com/BYU-Handwriting-Lab/ARUNetSegmentation.git

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python==3.7.3
    - tensorflow-gpu==2.1.0
    - pandas==1.0.3
    - pillow==7.1.2
    - matplotlib==3.2.1
    - tqdm==4.38
    - scikit-learn=0.22.1
    - shapely=1.7.0
  run:
    - python==3.7.3
    - tensorflow-gpu==2.1.0
    - pandas==1.0.3
    - pillow==7.1.2
    - matplotlib==3.2.1
    - tqdm==4.38

test:
  imports:
    - lineseg

about:
  home: https://github.com/BYU-Handwriting-Lab