package:
  name: lineseg
  version: 0.1

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python==3.7.3
    - tensorflow-gpu==2.1.0
    - pyyaml=5.3.1
    - pandas==1.0.3
    - pillow==7.1.2
    - scikit-learn==0.22.1
    - tqdm==4.38
    - matplotlib==3.2.1
  run:
    - python==3.7.3
    - tensorflow-gpu==2.1.0
    - pyyaml=5.3.1
    - pandas==1.0.3
    - pillow==7.1.2
    - scikit-learn==0.22.1
    - tqdm==4.38
    - matplotlib==3.2.1

test:
  imports:
    - lineseg

about:
  home: https://github.com/BYU-Handwriting-Lab